### ISSUE TITLE
Prerelease dependencies in stable version 2.0 

### ISSUE THREAD

**Issue by techteam-bln** [taefi/toggle-button-group#7]
Hi,
it would be nice when stable versions doesn't use prerelease versions of vaadin as dependency.
because not all have the option to use all possible maven repoositories.

It would be helpfull to use the stable bom from maven central.

`
<vaadin.version>**24.0.0.rc1**</vaadin.version>

 <dependency>
                <groupId>com.vaadin</groupId>
                <artifactId>vaadin-bom</artifactId>
                <type>pom</type>
                <scope>import</scope>
                <version>${vaadin.version}</version>
            </dependency>
`

**Comment by taefi** [comment]
Fixed in [`2.0.1`](https://vaadin.com/directory/component/toggle-button-group/2.0.1)
